import type { NextPage } from 'next'
import Head from 'next/head'
import { Container, Text, useMantineTheme } from '@mantine/core'
import { useScrollIntoView } from '@mantine/hooks'
import { useEffect } from 'react'

const Contact: NextPage = () => {
  const theme = useMantineTheme()

  const { targetRef, scrollIntoView } = useScrollIntoView<HTMLDivElement>()

  useEffect(() => {
    scrollIntoView({ alignment: 'center' })
  }, [scrollIntoView])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Container>
          <div ref={targetRef}>
            <Text p={theme.spacing.xl} size='xl'>
              This is the target for the scroll into view
            </Text>
          </div>
        </Container>
      </main>
    </>
  )
}

export default Contact
