import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Button, Card, Text, useMantineTheme } from '@mantine/core'
import { useScrollIntoView } from '@mantine/hooks'
import { Hero } from '../components/hero'
import { useEffect } from 'react'

const Contact: NextPage = () => {
  const theme = useMantineTheme()

  const { targetRef, scrollIntoView } = useScrollIntoView<HTMLDivElement>()

  useEffect(() => {
    scrollIntoView({ alignment: 'center' })
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='container'>
        <Hero />
        <Hero />
        <div ref={targetRef}>
          <Text p={theme.spacing.xl} size='xl'>
            This is the target for the scroll into view
          </Text>
        </div>
        <Hero />
      </main>
    </>
  )
}

export default Contact
